name: Deploy ADf ARM


on:
  workflow_dispatch:


jobs:
  review-changes-to-be-made:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.Review-this-step-for-changes-made.outputs }}
    steps:
    - name: Review-this-step-for-changes-made
      run: |
        echo ***These so and so pipelines will be removed from production***

  check-prev-step-to-review-changes:
    needs: review-changes-to-be-made
    environment: 
      name: main # Ensure people are notified of the changes in email to review
      url: ${{ needs.review-changes-to-be-made.outputs.output1 }}
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZCREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUB }}
        resourceGroupName: kjaprod
        template: ./adf-kjdemo/ARMTemplateForFactory.json
        parameters: ./adf-kjdemo/kjaprodParametersForFactory.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}