name: Deploy ADf ARM

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: '{ "clientId": ${{ secrets.CLIENTID }}, 
                "clientSecret": ${{ secrets.CLIENTSECRET }}, 
                "subscriptionId": ${{ secrets.SUB }},  
                "tenantId": ${{ secrets.TENANTID }}  
            }'

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUB }}
        resourceGroupName: kjaprod
        template: ./adf-kjdemo/ARMTemplateForFactory.json
        parameters: ./adf-kjdemo/kjaprodParametersForFactory.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}